"""empty message

Revision ID: 28537e8e5870
Revises: 3ec1d28c2303
Create Date: 2023-12-02 11:24:39.807328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28537e8e5870'
down_revision = '3ec1d28c2303'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('venue',
    sa.Column('venue_id', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('venue_id')
    )
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('venue_id', sa.String(), nullable=True))
        batch_op.create_foreign_key(None, 'venue', ['venue_id'], ['venue_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('venue_id')

    op.drop_table('venue')
    # ### end Alembic commands ###
