"""empty message

Revision ID: 5b312f606a3e
Revises: b9c2aac40b60
Create Date: 2023-11-29 00:49:02.036039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b312f606a3e'
down_revision = 'b9c2aac40b60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('speaker', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('speaker_bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('time', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('time')
        batch_op.drop_column('speaker_bio')
        batch_op.drop_column('speaker')

    # ### end Alembic commands ###
