"""empty message

Revision ID: 722c4a00db14
Revises: 
Create Date: 2023-11-23 02:03:49.342590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '722c4a00db14'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendees',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('ticket_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('ticket_id')
    )
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registrations',
    sa.Column('ticket_id', sa.String(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['attendees.ticket_id'], ),
    sa.PrimaryKeyConstraint('ticket_id', 'event_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registrations')
    op.drop_table('event')
    op.drop_table('attendees')
    # ### end Alembic commands ###
